# Generated by Django 5.0.7 on 2024-07-10 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='tenant',
            name='db_name',
            field=models.CharField(default='tenant1', max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.client'),
        ),
    ]
